


<<, cache=FALSE, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, results="hide">>=

require(stringi)
require(data.table)
require(FRAPO)
require(Hmisc)

require(magrittr)
require(PerformanceAnalytics)
require(RcppRoll)
require(ggplot2)
require(scales)
require(lubridate)


x<-list.files(
  path="figure",
  pattern="*.pdf",
  full.names=TRUE
)
if(length(x)>0)file.remove(x)

source("https://raw.githubusercontent.com/satrapade/utility/master/utility_functions.R")
source("https://raw.githubusercontent.com/satrapade/latex_utils/master/latex_helpers_v2.R")
source("https://raw.githubusercontent.com/satrapade/utility/master/tikz_shape.R")
source("https://raw.githubusercontent.com/satrapade/utility/master/nn_cast.R")

tret<- fread("N:/Depts/Share/UK Alpha Team/Analytics/test/hist_stock_data.csv") %>%
{.[,.(
    tret=tret[1],
    vol_30d=vol_30d[1],
    best_analyst_rating=best_analyst_rating[1],
    rsi30d=rsi30d[1],
    ma200=ma200[1],
    ma30=ma30[1],
    beta_plus=beta_plus[1],
    beta_minus=beta_minus[1],
    corr=corr[1]
  ),keyby=c("date","ticker")]} %>%
{.[!is.na(vol_30d)]} %>%
{.$date<-as.Date(.$date,format="%Y-%m-%d");.} %>%
{.$year_month<-as.character(.$date,format="%Y-%m");.}

countcurt<-function(x){
  maxx<-max(x)
  minx<-min(x)
  a<-mean(x)+(maxx-minx)/24
  b<-mean(x)-(maxx-minx)/24
  2*(sum(x>b)-sum(x>a))/length(x)-1
}

count_disasters<-function(x,q=0.1){
  the_range<-quantile(x,c(q,1-q))
  thresh<-min(the_range)+diff(the_range)*q
  sum(x<thresh)/length(x)
}

count_home_runs<-function(x,q=0.1){
  the_range<-quantile(x,c(q,1-q))
  thresh<-max(the_range)-diff(the_range)*q
  sum(x>thresh)/length(x)
}

fatness<-function(x,q=0.25){
  q_points<-c(q,1-q)
  diff(quantile(x,q_points))
}

fatness_ratio<-function(x,q1=0.25,q2=0.01){
  q1_points<-c(q1,1-q1)
  q1_diff<-diff(quantile(x,q1_points))
  q2_points<-c(q2,1-q2)
  q2_diff<-diff(quantile(x,q2_points))
  q2_diff/q1_diff
}

w<-tret[,.(
  date=as.Date(paste0(year_month,"-01"),format="%Y-%m-%d"),
  index_sd=sd(tret[ticker=="SXXP Index"]),
  cross_sectional_sd=sd(tret),
  sd_ratio=sd(tret)/sd(tret[ticker=="SXXP Index"]),
  mean_move=mean(abs(tret)),
  mean_lovol_move=mean(abs(tret[vol_30d<quantile(vol_30d,0.10)])),
  mean_hivol_move=mean(abs(tret[vol_30d>quantile(vol_30d,0.90)])),
  mean_lorating_move=local({
    i<-which(ticker!="SXXP Index" & !is.na(best_analyst_rating))
    if(length(i)<1)return(0)
    thresh<-quantile(best_analyst_rating[i],0.5)
    mean(tret[i][best_analyst_rating[i]<thresh])
  }),
  mean_hirating_move=local({
    i<-which(ticker!="SXXP Index" & !is.na(best_analyst_rating))
    if(length(i)<1)return(0)
    thresh<-quantile(best_analyst_rating[i],0.5)
    mean(tret[i][best_analyst_rating[i]>thresh])
  }),
  mean_hilorating_move=local({
    i<-which(ticker!="SXXP Index" & !is.na(best_analyst_rating))
    if(length(i)<1)return(0)
    hi_t<-quantile(best_analyst_rating[i],0.75)
    lo_t<-quantile(best_analyst_rating[i],0.25)
    mean(tret[i][best_analyst_rating[i]>hi_t])-mean(tret[i][best_analyst_rating[i]<lo_t])
  }),
  mean_lobetadiff_move=local({
    i<-which(ticker!="SXXP Index" & !is.na(beta_plus) & !is.na(beta_minus))
    if(length(i)<1)return(0)
    thresh<-quantile((beta_plus-beta_minus)[i],0.25)
    mean(tret[i][(beta_plus-beta_minus)[i]<thresh])
  }),
  mean_hibetadiff_move=local({
    i<-which(ticker!="SXXP Index" & !is.na(beta_plus) & !is.na(beta_minus))
    if(length(i)<1)return(0)
    thresh<-quantile((beta_plus-beta_minus)[i],0.75)
    mean(tret[i][(beta_plus-beta_minus)[i]>thresh])
  }),
  hivol_lovol_ratio=quantile(vol_30d,c(0.1,0.90)) %>% 
    {mean(abs(tret[vol_30d>.[2]]))/mean(abs(tret[vol_30d<.[1]]))},
  hivol_lovol_diff=quantile(vol_30d,c(0.1,0.90)) %>% 
    {mean(abs(tret[vol_30d>.[2]]))-mean(abs(tret[vol_30d<.[1]]))} %>%
    {./mean(abs(tret[ticker=="SXXP Index"]))},
  hivol_sxxp_ratio=quantile(vol_30d,0.90) %>% 
    {mean(abs(tret[vol_30d>.]))/mean(abs(tret[ticker=="SXXP Index"]))},
  lovol_sxxp_ratio=quantile(vol_30d,0.1) %>% 
    {mean(abs(tret[vol_30d>.]))/mean(abs(tret[ticker=="SXXP Index"]))},
  hist_daily_rank_cor=cor(abs(tret),vol_30d,method="spearman"),
  lovol_breadth=mean(sign(tret[vol_30d<quantile(vol_30d,0.10)])),
  hivol_breadth=mean(sign(tret[vol_30d>quantile(vol_30d,0.90)])),
  count_disasters=count_disasters(tret,q=0.1),
  count_home_runs=count_home_runs(tret,q=0.1),
  dispersion_01=fatness(tret,q=0.01),
  dispersion_05=fatness(tret,q=0.05),
  dispersion_25=fatness(tret,q=0.25),
  sd_hivol=sd(tret[vol_30d>quantile(vol_30d,0.9)]),
  sd_lovol=sd(tret[vol_30d<quantile(vol_30d,0.1)]),
  breadth=mean(sign(tret)),
  breadth_hivol=which(vol_30d>quantile(vol_30d,0.90)) %>% {mean(sign(tret[.]))},
  breadth_lovol=which(vol_30d>quantile(vol_30d,0.10)) %>% {mean(sign(tret[.]))},
  breadth=mean(sign(tret)),
  upmove=if(sum(tret>0)>0){mean(tret[tret>0])}else{0},
  dnmove=if(sum(tret<0)>0){mean(abs(tret[tret<0]))}else{0},
  count=length(tret)
),keyby=year_month][count>1000]

data1<-c("dispersion_01","dispersion_05","dispersion_25","cross_sectional_sd")
data2<-c("count_disasters","count_home_runs","count_skew")
data3<-c("count_skew")
data4<-c("mean_lovol_move","mean_hivol_move")
data5<-c("hivol_lovol_ratio")
data6<-c("upmove","dnmove")
data7<-c("updn_diff")
data8<-c("lovol_breadth","hivol_breadth")


calc_stats<-function(dt,jtxt,g="year_month"){
  stats<-c(jtxt,c(count="length(tret)",date="as.Date(paste0(year_month,'-01'),format='%Y-%m-%d')"))
  stats_expr_txt<-paste0("list(",paste0(names(stats),"=",stats,collapse=","),")")
  jexpr<-parse(text=stats_expr_txt)[[1]]
  dt_expr<-bquote(dt[,.(jexpr),keyby=.(g)])
  res0<-eval(dt_expr)
  res1<-res0[count>1000]
  res2<-melt(res1,id.vars="date",measure.vars=names(jtxt))
  res2
}

plot_stats<-function(stats){
  stats %>%
  ggplot() + 
  geom_line(aes(x=date,y=value,col=variable)) + 
  scale_x_date(date_breaks = "1 years" , date_labels = "%y")+
  ggtitle(paste0(sort(unique(stats$variable)),collapse=", "))
}

latex_stats<-function(dt,jtxt){
  stats<-calc_stats(dt,jtxt)
  g<-plot_stats(stats)
  paste0(
    "\\begin{center}",
    ntable(
      df=data.table(
        stat=latexTranslate(names(jtxt)),
        calculation=paste("{\\tt ",latexTranslate(jtxt)," }")
      )
    ),
    "\\end{center}",
    "\\begin{center}",
    make_plot(plot(g),width="20cm",height="20cm",envir=environment()),
    "\\end{center}",
    collapse="\n"
  )
}


make_stat_plot<-function(start_date,stats)w[date>=as.Date(start_date)] %>% 
  melt(
    id.vars="date",
    measure.vars=stats
  ) %>%
  ggplot() + 
  geom_line(aes(x=date,y=value,col=variable)) + 
  scale_x_date(date_breaks = "1 years" , date_labels = "%y")+
  ggtitle(paste0(stats,collapse=", "))


@
\documentclass{article}

\usepackage[portrait, headheight = 0cm, margin=0.25cm, top = 0.25cm, nofoot]{geometry} 
\usepackage[export]{adjustbox} 
\usepackage{graphicx}
\usepackage[space]{grffile}
\usepackage[dvipsnames,table]{xcolor} % [dvipsnames,table] for setting colors \usepackage{amsmath} \usepackage{xfrac}
\usepackage{tikz}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{shapes.misc}
\usetikzlibrary{arrows}
\usepackage{xfrac}
\usepackage{hyperref}
\usepackage{amsmath}

\DeclareRobustCommand\Tstrut{\rule{0pt}{2.6ex}}         % = `top' strut
\DeclareRobustCommand\Bstrut{\rule[-0.9ex]{0pt}{0pt}}   % = `bottom' strut
\renewcommand{\familydefault}{\sfdefault}


\begin{document}

\tableofcontents

\newpage
\section{Summary}
\vskip 5mm

\begin{itemize}
\item We examine a number of cross sectional statistics of daily returns of SXXP memeber stocks
\item SXXP members are sampled quarterly and their daily returns for the preceding 3 month are
retrieved from Bloomberg 
\item We split the resulting return data by month and compute a number of statistics for each group
\end{itemize}

\vskip 5mm

items in dataset:

\vskip 5mm

\begin{center}
\Sexpr{ntable(
  df=data.table(
    item=latexTranslate(names(tret)),
    type=mapply(class,tret)
  )
)}
\end{center}

\newpage
\section{mean absolute move, mean move}
\Sexpr{latex_stats(dt=tret,jtxt=c(mean_abs_move="mean(abs(tret))",mean_move="mean(tret)"))}

\newpage
\section{upmove, downmove}
\Sexpr{latex_stats(dt=tret,jtxt=c(upmove="mean(tret[tret>0])",downmove="mean(-tret[tret<0])"))}

\newpage
\section{dispersion}
\Sexpr{latex_stats(
  dt=tret,
  jtxt=c(
    dispersion_01="diff(quantile(tret,c(0.01,0.99)))",
    dispersion_05="diff(quantile(tret,c(0.05,0.95)))",
    dispersion_25="diff(quantile(tret,c(0.25,0.75)))",
    sd="sd(tret)"
  )
)}


\newpage
\section{correlation of returns and rating}
<<, cache=FALSE, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, results="hide">>=
safe_cor<-function(x,y,method){
  i<-which(!is.na(x)&!is.na(y))
  cor(x[i],y[i],method = method)
}
@
\Sexpr{latex_stats(
  dt=tret,
  jtxt=c(
    rating_corr="safe_cor(tret,best_analyst_rating,method='spearman')"
  )
)}

\newpage
\section{correlation of realized volatility and rating}
<<, cache=FALSE, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, results="hide">>=
safe_cor<-function(x,y,method){
  i<-which(!is.na(x)&!is.na(y))
  cor(x[i],y[i],method = method)
}
@
\Sexpr{latex_stats(
  dt=tret,
  jtxt=c(
    rating_corr="safe_cor(vol_30d,best_analyst_rating,method='spearman')"
  )
)}

\newpage
\section{correlation of trend and rating}
<<, cache=FALSE, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, results="hide">>=
safe_cor<-function(x,y,method){
  i<-which(!is.na(x)&!is.na(y))
  cor(x[i],y[i],method = method)
}
@
\Sexpr{latex_stats(
  dt=tret,
  jtxt=c(
    rating_corr="safe_cor((ma30-ma200)/ma200,best_analyst_rating,method='spearman')"
  )
)}


\newpage
\section{correlation of 1m realized volatility and size of daily move}
<<, cache=FALSE, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, results="hide">>=
safe_cor<-function(x,y,method){
  i<-which(!is.na(x)&!is.na(y))
  cor(x[i],y[i],method = method)
}
@
\Sexpr{latex_stats(
  dt=tret,
  jtxt=c(
    rating_corr="safe_cor(abs(tret),vol_30d,method='spearman')"
  )
)}

\newpage
\section{mean abs lovol, hivol move}
\Sexpr{latex_stats(
  dt=tret,
  jtxt=c(
    mean_lovol_move="mean(tret[vol_30d<quantile(vol_30d,0.25)])",
    mean_hivol_move="mean(tret[vol_30d>quantile(vol_30d,0.75)])"
  )
)}

\newpage
\section{mean abs lovol, hivol move}
\Sexpr{latex_stats(
  dt=tret,
  jtxt=c(
    mean_abs_lovol_move="mean(abs(tret[vol_30d<quantile(vol_30d,0.25)]))",
    mean_abs_hivol_move="mean(abs(tret[vol_30d>quantile(vol_30d,0.75)]))"
  )
)}
  
\newpage
\section{beta plus, beta minus}
\Sexpr{latex_stats(
  dt=tret,
  jtxt=c(
    mean_beta_plus="mean(beta_plus[!is.na(beta_plus)])",
    mean_beta_minus="mean(beta_minus[!is.na(beta_minus)])"
  )
)}
    
\newpage
\section{analyst ratings}
\Sexpr{latex_stats(
  dt=tret,
  jtxt=c(
    analyst_rating="mean(best_analyst_rating[!is.na(best_analyst_rating)])"
  )
)}
  
\newpage
\section{rsi}
\Sexpr{latex_stats(
  dt=tret,
  jtxt=c(
    rsi30d="mean(rsi30d[!is.na(rsi30d)])"
  )
)}  

\newpage
\section{corr}
\Sexpr{latex_stats(
  dt=tret,
  jtxt=c(
    corr="mean(corr[!is.na(corr)])"
  )
)}  

\newpage
\section{breadth}
\Sexpr{latex_stats(
  dt=tret,
  jtxt=c(
    corr="mean(sign(tret))"
  )
)}  

\newpage
\section{analyst rating factor basket}
<<, cache=FALSE, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, results="hide">>=
position_on_factor<-function(tret,factor,q){
  i<-which(!is.na(tret)&!is.na(factor))
  short <- ifelse(factor[i]<quantile(factor[i],q),-1,0)
  long  <- ifelse(factor[i]>quantile(factor[i],1-q),1,0)
  tret[i]*(short+long)
}
@
\Sexpr{latex_stats(
  dt=tret,
  jtxt=c(
    analyst_factor="mean(position_on_factor(tret-0.5*(beta_plus+beta_minus)*(ticker=='SXXP Index')*tret,best_analyst_rating,0.25))"
  )
)}


\newpage
\section{mean streak, days}
<<, cache=FALSE, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, results="hide">>=
mean_streak<-
tret[,.SD,keyby="date"][,.(
  max_streak=local({
        change_sign<-abs(diff(sign(tret)))>0
        change_loc<-which(change_sign)
        if(length(change_loc)<2)return(0L)
        max(diff(change_loc))
  })
),keyby=c("year_month","ticker")][,.(
    date=as.Date(paste0(year_month,"-01")),
    mean_max_streak=mean(max_streak)
  ),
  keyby="year_month"
]


gg_mean_streak <- mean_streak[mean_max_streak>0] %>%
  ggplot() + 
  geom_point(aes(x=date,y=mean_max_streak)) + 
  geom_hline(yintercept = mean(mean_streak[mean_max_streak>0,mean_max_streak])) +
  scale_x_date(date_breaks = "1 years" , date_labels = "%y")+
  ggtitle("mean max streak, days")

@
\begin{center}
\Sexpr{make_plot(plot(gg_mean_streak),width="20cm",height="20cm",envir=environment())}
\end{center}

\end{document}





